import { DocumentoTipo } from '@/types/enums'

export interface WorkflowStep {
    nextTypes: DocumentoTipo[]
    isMandatory: boolean
    autoGenerated?: DocumentoTipo[]
    description: string
    note?: string
}

export const DOCUMENT_WORKFLOW: Partial<Record<DocumentoTipo, WorkflowStep>> = {
    [DocumentoTipo.ORDEN_SERVICIO]: {
        nextTypes: [DocumentoTipo.DIAGNOSTICO_PRESUPUESTO],
        isMandatory: true,
        description: 'Siguiente: Diagnóstico y Presupuesto',
        note: 'Se debe realiar el diagnóstico técnico para generar un presupuesto.',
    },
    [DocumentoTipo.DIAGNOSTICO_PRESUPUESTO]: {
        nextTypes: [
            DocumentoTipo.ACEPTACION_PRESUPUESTO,
            DocumentoTipo.RECHAZO_PRESUPUESTO
        ],
        isMandatory: true,
        description: 'Esperando respuesta del cliente',
        note: 'El cliente debe Aceptar o Rechazar el presupuesto propuesto.',
    },
    [DocumentoTipo.ACEPTACION_PRESUPUESTO]: {
        nextTypes: [DocumentoTipo.ALBARAN_ENTREGA],
        autoGenerated: [DocumentoTipo.FACTURA],
        isMandatory: true,
        description: 'Siguiente: Albarán de Entrega (Obligatorio)',
        note: 'Al generar el Albarán de Entrega, se generará la Factura automáticamente.',
    },
    [DocumentoTipo.RECHAZO_PRESUPUESTO]: {
        nextTypes: [DocumentoTipo.ALBARAN_ENTREGA],
        autoGenerated: [DocumentoTipo.FACTURA],
        isMandatory: true,
        description: 'Siguiente: Albarán de Devolución',
        note: 'Se debe entregar el equipo y generar factura por diagnóstico si aplica.',
    },
    [DocumentoTipo.EXTENSION_PRESUPUESTO]: {
        nextTypes: [
            DocumentoTipo.ACEPTACION_EXTENSION // Assuming extension also needs acceptance per logic, though user prompt jumped to Albaran. 
            // "En algún caso puede existir una extensión de presupuesto que conllevará Albarán de entrega y factura."
            // Usually extension needs acceptance first. But I will follow user flow strictly if possible.
            // Let's add Acceptance for extension to be safe, but link it to delivery in the prompt context.
        ],
        isMandatory: true,
        description: 'Requiere Aceptación de Extensión',
        note: 'Tras la aceptación, se procederá al Albarán de Entrega y Factura.',
    },
    [DocumentoTipo.ACEPTACION_EXTENSION]: {
        nextTypes: [DocumentoTipo.ALBARAN_ENTREGA],
        autoGenerated: [DocumentoTipo.FACTURA],
        isMandatory: true,
        description: 'Siguiente: Albarán de Entrega',
        note: 'Al generar el Albarán, se incluirán los items de la extensión en la factura.',
    }
}

export const getWorkflowStatus = (type: DocumentoTipo) => {
    return DOCUMENT_WORKFLOW[type] || null
}
