
// Datos compartidos para seeding (API y Base de datos)

export const usuariosSeed = [
    // Clientes
    {
        id: 'cliente-1',
        nombre: 'Juan',
        apellidos: 'Pérez García',
        email: 'juan.perez@email.com',
        password: 'hashed_password_1',
        rol: 'cliente',
        telefono: '655-123-456',
        direccion: 'Calle Mayor 123, 28001 Madrid',
        nif: '12345678A',
        fechaNacimiento: '1990-05-15',
        activo: true,
        fechaRegistro: '2023-01-15T10:30:00Z'
    },
    {
        id: 'cliente-2',
        nombre: 'María',
        apellidos: 'García Rodríguez',
        email: 'maria.garcia@email.com',
        password: 'hashed_password_2',
        rol: 'cliente',
        telefono: '655-234-567',
        direccion: 'Avenida Libertad 45, 08010 Barcelona',
        nif: '87654321B',
        fechaNacimiento: '1988-08-22',
        activo: true,
        fechaRegistro: '2023-02-20T09:15:00Z'
    },
    {
        id: 'cliente-3',
        nombre: 'Carlos',
        apellidos: 'López Martínez',
        email: 'carlos.lopez@email.com',
        password: 'hashed_password_3',
        rol: 'cliente',
        telefono: '655-345-678',
        direccion: 'Calle San Juan 67, 41003 Sevilla',
        nif: '76543210C',
        fechaNacimiento: '1992-03-10',
        activo: true,
        fechaRegistro: '2023-03-10T16:45:00Z'
    },
    {
        id: 'cliente-4',
        nombre: 'Ana',
        apellidos: 'Martínez Sánchez',
        email: 'ana.martinez@email.com',
        password: 'hashed_password_4',
        rol: 'cliente',
        telefono: '655-456-789',
        direccion: 'Paseo de la Reforma 23, 50007 Zaragoza',
        nif: '65432109D',
        fechaNacimiento: '1989-11-28',
        activo: true,
        fechaRegistro: '2023-04-05T14:20:00Z'
    },
    {
        id: 'cliente-5',
        nombre: 'Diego',
        apellidos: 'Fernández López',
        email: 'diego.fernandez@email.com',
        password: 'hashed_password_5',
        rol: 'cliente',
        telefono: '655-567-890',
        direccion: 'Calle Principal 89, 28002 Madrid',
        nif: '54321098E',
        fechaNacimiento: '1991-07-18',
        activo: true,
        fechaRegistro: '2023-05-12T11:30:00Z'
    },

    // Técnicos
    {
        id: 'tecnico-1',
        nombre: 'Carlos',
        apellidos: 'García Fernández',
        email: 'carlos.garcia@microinfo.es',
        password: 'hashed_password_tecnico_1',
        rol: 'tecnico',
        telefono: '655-111-222',
        direccion: 'Calle Técnicos 1, 28001 Madrid',
        nif: '11111111A',
        especialidades: ['Hardware', 'Portátiles', 'SSD', 'HDD'],
        nivelExperiencia: 10,
        nivel: 'experto',
        disponible: true,
        recibirNotificaciones: true,
        fechaRegistro: '2020-01-15T08:00:00Z',
        ultimaConexion: '2023-12-30T09:00:00Z',
        ticketsAsignados: 3,
        ticketsResueltos: 45,
        valoracionMedia: 4.8,
        valoraciones: 23
    },
    {
        id: 'tecnico-2',
        nombre: 'María',
        apellidos: 'Martínez Sánchez',
        email: 'maria.martinez@microinfo.es',
        password: 'hashed_password_tecnico_2',
        rol: 'tecnico',
        telefono: '655-222-333',
        direccion: 'Calle Técnicos 2, 08010 Barcelona',
        nif: '22222222B',
        especialidades: ['Monitores', 'Periféricos', 'Audio'],
        nivelExperiencia: 7,
        nivel: 'senior',
        disponible: true,
        recibirNotificaciones: true,
        fechaRegistro: '2021-06-20T09:00:00Z',
        ultimaConexion: '2023-12-30T08:30:00Z',
        ticketsAsignados: 2,
        ticketsResueltos: 38,
        valoracionMedia: 4.9,
        valoraciones: 20
    },
    {
        id: 'tecnico-3',
        nombre: 'Diego',
        apellidos: 'Fernández López',
        email: 'diego.fernandez@microinfo.es',
        password: 'hashed_password_tecnico_3',
        rol: 'tecnico',
        telefono: '655-333-444',
        direccion: 'Calle Técnicos 3, 41003 Sevilla',
        nif: '33333333C',
        especialidades: ['CPU', 'GPU', 'RAM'],
        nivelExperiencia: 5,
        nivel: 'senior',
        disponible: false,
        recibirNotificaciones: true,
        fechaRegistro: '2022-03-10T08:00:00Z',
        ultimaConexion: '2023-12-29T16:45:00Z',
        ticketsAsignados: 5,
        ticketsResueltos: 52,
        valoracionMedia: 4.7,
        valoraciones: 18
    },
    {
        id: 'tecnico-4',
        nombre: 'Ana',
        apellidos: 'Rodríguez González',
        email: 'ana.rodriguez@microinfo.es',
        password: 'hashed_password_tecnico_4',
        rol: 'tecnico',
        telefono: '655-444-555',
        direccion: 'Calle Técnicos 4, 50007 Zaragoza',
        nif: '44444444D',
        especialidades: ['Almacenamiento', 'RAM'],
        nivelExperiencia: 2,
        nivel: 'junior',
        disponible: true,
        recibirNotificaciones: true,
        fechaRegistro: '2023-09-01T08:00:00Z',
        ultimaConexion: '2023-12-30T10:00:00Z',
        ticketsAsignados: 1,
        ticketsResueltos: 12,
        valoracionMedia: 4.5,
        valoraciones: 10
    },

    // Administradores
    {
        id: 'admin-1',
        nombre: 'Admin',
        apellidos: 'Principal',
        email: 'admin@microinfo.es',
        password: 'hashed_password_admin_1',
        rol: 'admin',
        telefono: '900-123-456',
        direccion: 'Calle Admin 1, 28001 Madrid',
        nif: '99999999Z',
        fechaRegistro: '2019-01-01T08:00:00Z',
        activo: true
    },
    {
        id: 'admin-2',
        nombre: 'Ana',
        apellidos: 'Admin',
        email: 'ana.admin@microinfo.es',
        password: 'hashed_password_admin_2',
        rol: 'admin',
        telefono: '900-234-567',
        direccion: 'Calle Admin 2, 08010 Barcelona',
        nif: '88888888Y',
        fechaRegistro: '2020-06-15T08:00:00Z',
        activo: true
    }
]

// Productos de prueba
export const productosSeed = [
    {
        id: 'prod-1',
        sku: 'LAP-GAM-X15',
        nombre: 'Portátil Gaming Pro X15',
        descripcionCorta: 'Intel Core i7-13700H, RTX 4070, 32GB RAM DDR5',
        descripcionLarga: 'Portátil gaming de alto rendimiento con Intel Core i7 de 13ª generación, NVIDIA GeForce RTX 4070 de 8GB, 32GB de RAM DDR5 a 6000MHz, SSD NVMe de 1TB y pantalla de 15.6" QHD 240Hz. Incluye Windows 11 Home preinstalado y 2 años de garantía.',
        precio: 1499,
        precioOferta: 1299,
        stock: 12,
        stockMinimo: 5,
        categoria: 'ordenadores',
        marca: 'Asus',
        modelo: 'ROG Strix G15',
        imagen: '/images/producto_laptop_gaming.png',
        imagenes: ['/images/producto_laptop_gaming.png', '/images/producto_laptop_gaming_2.png'],
        enOferta: true,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-12-15T10:00:00Z',
        fechaActualizacion: '2023-12-28T15:30:00Z'
    },
    {
        id: 'prod-2',
        sku: 'SSD-SAM-2TB',
        nombre: 'SSD NVMe Samsung 980 Pro 2TB',
        descripcionCorta: 'Velocidad de lectura 7450MB/s, escritura 6900MB/s',
        descripcionLarga: 'SSD NVMe de última generación de Samsung con tecnología V-NAND y controlador Samsung. Velocidades de lectura de hasta 7450MB/s y escritura de hasta 6900MB/s. Durabilidad de hasta 1.200TBW. Compatible con PCIe 4.0 y PCIe 3.0.',
        precio: 329.99,
        precioOferta: 289.99,
        stock: 8,
        stockMinimo: 5,
        categoria: 'almacenamiento',
        marca: 'Samsung',
        modelo: '980 Pro',
        imagen: '/images/producto_ssd.png',
        imagenes: ['/images/producto_ssd.png', '/images/producto_ssd_2.png'],
        enOferta: true,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-12-10T09:00:00Z',
        fechaActualizacion: '2023-12-20T11:15:00Z'
    },
    {
        id: 'prod-3',
        sku: 'RAM-COR-DD5-32',
        nombre: 'Memoria RAM DDR5 32GB Corsair Vengeance',
        descripcionCorta: '6000MHz CL36 RGB con dissipador de calor',
        descripcionLarga: 'Memoria RAM DDR5 de 32GB Corsair Vengeance RGB con velocidad de 6000MHz y latencia CL36. Incluye dissipador de calor RGB integrado para mantener el módulo fresco incluso bajo carga intensiva. Compatible con placas base Intel y AMD de última generación.',
        precio: 169.99,
        precioOferta: 149.99,
        stock: 15,
        stockMinimo: 5,
        categoria: 'ram',
        marca: 'Corsair',
        modelo: 'Vengeance DDR5',
        imagen: '/images/producto_ram.png',
        imagenes: ['/images/producto_ram.png', '/images/producto_ram_2.png'],
        enOferta: true,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-12-08T11:30:00Z',
        fechaActualizacion: '2023-12-18T14:45:00Z'
    },
    {
        id: 'prod-4',
        sku: 'MON-SAM-32-4K',
        nombre: 'Monitor Curvo 32" 4K Samsung Odyssey G7',
        descripcionCorta: '165Hz, 1ms, HDR10+, AMD FreeSync Premium Pro',
        descripcionLarga: 'Monitor curvo de 32" con resolución 4K UHD (3840x2160) y frecuencia de actualización de 165Hz. Tiempo de respuesta de 1ms MPRT, HDR10+ para soporte de HDR10 y AMD FreeSync Premium Pro. Incluye altura ajustable, inclinación y rotación. Puerto HDMI 2.1 y DisplayPort 1.4.',
        precio: 749.99,
        precioOferta: null,
        stock: 3,
        stockMinimo: 3,
        categoria: 'perifericos',
        marca: 'Samsung',
        modelo: 'Odyssey G7',
        imagen: '/images/producto_monitor.png',
        imagenes: ['/images/producto_monitor.png'],
        enOferta: false,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-12-05T10:00:00Z',
        fechaActualizacion: '2023-12-05T10:00:00Z'
    },
    {
        id: 'prod-5',
        sku: 'CPU-INT-i9',
        nombre: 'CPU Intel Core i9-13900K',
        descripcionCorta: '24 núcleos (8P+16E), 32 hilos, 5.8GHz Turbo',
        descripcionLarga: 'Procesador Intel Core i9-13900K de 13ª generación con 24 núcleos (8 de rendimiento y 16 de eficiencia), 32 hilos y frecuencia turbo de hasta 5.8GHz. Incluye L3 de 36MB, DDR5 y PCIe 5.0. Disipador de calor en caja incluido. Compatible con placas base Z790 y Z690.',
        precio: 649.99,
        precioOferta: null,
        stock: 5,
        stockMinimo: 3,
        categoria: 'componentes',
        marca: 'Intel',
        modelo: 'Core i9-13900K',
        imagen: '/images/producto_cpu.png',
        imagenes: ['/images/producto_cpu.png'],
        enOferta: false,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-12-01T09:00:00Z',
        fechaActualizacion: '2023-12-01T09:00:00Z'
    },
    {
        id: 'prod-6',
        sku: 'GPU-NV-RTX4080',
        nombre: 'NVIDIA GeForce RTX 4080 16GB',
        descripcionCorta: '16GB GDDR6X, 24GB/s, 9600 CUDA cores',
        descripcionLarga: 'Tarjeta gráfica NVIDIA GeForce RTX 4080 con 16GB de memoria GDDR6X de ultra alta velocidad y ancho de banda de 24GB/s. 9600 núcleos CUDA para IA y renderizado. Compatible con DirectX 12 Ultimate, OpenGL 4.6 y Vulkan 1.3. Incluye soporte NVIDIA DLSS 3.0.',
        precio: 1899,
        precioOferta: null,
        stock: 2,
        stockMinimo: 2,
        categoria: 'componentes',
        marca: 'NVIDIA',
        modelo: 'GeForce RTX 4080',
        imagen: '/images/producto_gpu.png',
        imagenes: ['/images/producto_gpu.png', '/images/producto_gpu_2.png'],
        enOferta: false,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-11-28T10:00:00Z',
        fechaActualizacion: '2023-11-28T10:00:00Z'
    },
    {
        id: 'prod-7',
        sku: 'KB-LOG-G915',
        nombre: 'Teclado Mecánico Logitech G915 LIGHTSPEED',
        descripcionCorta: 'Teclado inalámbrico RGB de perfil bajo, switches GL Táctil',
        descripcionLarga: 'El G915 es una proeza de ingeniería y diseño, con tecnología inalámbrica LIGHTSPEED de nivel profesional, RGB LIGHTSYNC avanzada y nuevos interruptores mecánicos de perfil bajo y alto rendimiento. Fabricado meticulosamente con materiales de primera calidad, el G915 es un diseño increíblemente refinado de belleza, resistencia y rendimiento inigualables.',
        precio: 249.99,
        precioOferta: 199.99,
        stock: 10,
        stockMinimo: 3,
        categoria: 'perifericos',
        marca: 'Logitech',
        modelo: 'G915',
        imagen: '/images/producto_teclado.png',
        imagenes: ['/images/producto_teclado.png'],
        enOferta: true,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-11-20T12:00:00Z',
        fechaActualizacion: '2023-11-20T12:00:00Z'
    },
    {
        id: 'prod-8',
        sku: 'MS-LOG-G502',
        nombre: 'Ratón Gaming Logitech G502 HERO',
        descripcionCorta: 'Sensor HERO 25K, 11 botones programables, pesas ajustables',
        descripcionLarga: 'G502 HERO cuenta con un sensor óptico avanzado para máxima precisión de seguimiento, iluminación RGB personalizada, perfiles de juego personalizados, desde 200 hasta 25.600 dpi y pesas reposicionables.',
        precio: 89.99,
        precioOferta: 59.99,
        stock: 25,
        stockMinimo: 10,
        categoria: 'perifericos',
        marca: 'Logitech',
        modelo: 'G502 HERO',
        imagen: '/images/producto_raton.png',
        imagenes: ['/images/producto_raton.png'],
        enOferta: true,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-11-15T09:30:00Z',
        fechaActualizacion: '2023-11-15T09:30:00Z'
    },
    {
        id: 'prod-9',
        sku: 'MB-ASU-Z790',
        nombre: 'Placa Base ASUS ROG Maximus Z790 Hero',
        descripcionCorta: 'LGA 1700, DDR5, PCIe 5.0, Wi-Fi 6E',
        descripcionLarga: 'La ROG Maximus Z790 Hero es una placa base de gama alta con soporte para procesadores Intel Core de 13ª y 12ª generación. Cuenta con un robusto sistema de alimentación, soporte para memoria DDR5 de alta velocidad, múltiples ranuras M.2 con disipadores, y conectividad de última generación con Wi-Fi 6E y Ethernet de 2.5Gb.',
        precio: 689.99,
        precioOferta: null,
        stock: 5,
        stockMinimo: 2,
        categoria: 'componentes',
        marca: 'ASUS',
        modelo: 'ROG Maximus Z790 Hero',
        imagen: '/images/producto_placa_base.jpg',
        imagenes: ['/images/producto_placa_base.jpg'],
        enOferta: false,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-11-10T08:00:00Z',
        fechaActualizacion: '2023-11-10T08:00:00Z'
    },
    {
        id: 'prod-10',
        sku: 'PSU-COR-850',
        nombre: 'Fuente Corsair RM850x 850W 80 Plus Gold',
        descripcionCorta: 'Totalmente modular, Ventilador con levitación magnética',
        descripcionLarga: 'Las fuentes de alimentación totalmente modulares de la serie CORSAIR RM850x se han fabricado con los componentes de la mejor calidad para proporcionar a su PC una alimentación con eficiencia 80 PLUS Gold y un funcionamiento silencioso gracias a los ventiladores con levitación magnética.',
        precio: 154.99,
        precioOferta: 139.99,
        stock: 12,
        stockMinimo: 5,
        categoria: 'componentes',
        marca: 'Corsair',
        modelo: 'RM850x',
        imagen: '/images/producto_fuente.jpg',
        imagenes: ['/images/producto_fuente.jpg'],
        enOferta: true,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-11-05T14:20:00Z',
        fechaActualizacion: '2023-11-05T14:20:00Z'
    },
    {
        id: 'prod-11',
        sku: 'HDD-SEA-8TB',
        nombre: 'Disco Duro Seagate IronWolf 8TB NAS',
        descripcionCorta: 'SATA 6Gb/s, 7200 RPM, 256MB caché, diseñado para NAS',
        descripcionLarga: 'IronWolf está diseñado para todo lo relacionado con el almacenamiento en red (NAS). Acostúmbrese a un rendimiento robusto, listo para usar y escalable las 24 horas del día, los 7 días de la semana, que puede manejar entornos multiusuario y altas tasas de carga de trabajo.',
        precio: 219.99,
        precioOferta: null,
        stock: 15,
        stockMinimo: 5,
        categoria: 'almacenamiento',
        marca: 'Seagate',
        modelo: 'IronWolf 8TB',
        imagen: '/images/producto_hdd.png',
        imagenes: ['/images/producto_hdd.png'],
        enOferta: false,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-11-01T10:00:00Z',
        fechaActualizacion: '2023-11-01T10:00:00Z'
    },
    {
        id: 'prod-12',
        sku: 'LAP-DEL-XPS13',
        nombre: 'Portátil Dell XPS 13 9315',
        descripcionCorta: 'Intel Core i7, 16GB RAM, 512GB SSD, Pantalla 13.4" FHD+',
        descripcionLarga: 'El XPS 13 es nuestro portátil de 13 pulgadas más pequeño y fino. Está diseñado para un estilo de vida móvil con una batería de larga duración y un diseño elegante fabricado con aluminio mecanizado CNC de alta calidad.',
        precio: 1299.99,
        precioOferta: 1099.99,
        stock: 6,
        stockMinimo: 2,
        categoria: 'ordenadores',
        marca: 'Dell',
        modelo: 'XPS 13',
        imagen: '/images/producto_laptop_xps.jpg',
        imagenes: ['/images/producto_laptop_xps.jpg'],
        enOferta: true,
        activo: true,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2023-10-25T11:00:00Z',
        fechaActualizacion: '2023-10-25T11:00:00Z'
    },
    {
        id: 'prod-13',
        sku: 'HS-LOG-PRO-X',
        nombre: 'Auriculares Logitech G PRO X Wireless',
        descripcionCorta: 'Tecnología LIGHTSPEED, DTS Headphone:X 2.0, Blue VO!CE',
        descripcionLarga: 'Los auriculares con micrófono para gaming PRO X inalámbricos. Rendimiento de nivel profesional con tecnología LIGHTSPEED inalámbrica de 2,4 GHz, una duración de batería de más de 20 horas y un radio de acción de más de 13 metros.',
        precio: 219.99,
        precioOferta: 189.99,
        stock: 8,
        stockMinimo: 3,
        categoria: 'audio',
        marca: 'Logitech',
        modelo: 'G PRO X Wireless',
        imagen: '/images/producto_auriculares_pro.jpg',
        imagenes: ['/images/producto_auriculares_pro.jpg'],
        enOferta: true,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2024-01-05T10:00:00Z',
        fechaActualizacion: '2024-01-05T10:00:00Z'
    },
    {
        id: 'prod-14',
        sku: 'MB-MSI-B650',
        nombre: 'Placa Base MSI MAG B650 Tomahawk WiFi',
        descripcionCorta: 'Socket AM5, DDR5, PCIe 4.0, Wi-Fi 6E',
        descripcionLarga: 'La serie MAG lucha junto a los jugadores en busca del honor. Con elementos de inspiración militar añadidos en estos productos de juego, renacen como el símbolo de la robustez y la durabilidad.',
        precio: 235.99,
        precioOferta: 215.00,
        stock: 6,
        stockMinimo: 2,
        categoria: 'componentes',
        marca: 'MSI',
        modelo: 'MAG B650 Tomahawk WiFi',
        imagen: '/images/producto_placa_amd.jpg',
        imagenes: ['/images/producto_placa_amd.jpg'],
        enOferta: true,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2024-01-08T09:00:00Z',
        fechaActualizacion: '2024-01-08T09:00:00Z'
    },
    {
        id: 'prod-15',
        sku: 'LAP-LEN-LEG5',
        nombre: 'Portátil Lenovo Legion Slim 5 Gen 8',
        descripcionCorta: 'AMD Ryzen 7 7840HS, RTX 4060, 16GB RAM, 512GB SSD',
        descripcionLarga: 'Disfruta de la libertad de jugar en cualquier lugar con el Lenovo Legion Slim 5. Este portátil combina un rendimiento potente con un diseño fino y ligero, ideal para jugadores y creadores que no se detienen.',
        precio: 1399.00,
        precioOferta: 1149.00,
        stock: 4,
        stockMinimo: 2,
        categoria: 'ordenadores',
        marca: 'Lenovo',
        modelo: 'Legion Slim 5',
        imagen: '/images/producto_laptop_legion.jpg',
        imagenes: ['/images/producto_laptop_legion.jpg'],
        enOferta: true,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2024-01-10T11:00:00Z',
        fechaActualizacion: '2024-01-10T11:00:00Z'
    },
    {
        id: 'prod-16',
        sku: 'MON-LG-27-GP',
        nombre: 'Monitor LG UltraGear 27GR75Q-B 27"',
        descripcionCorta: 'QHD (2560x1440), 165Hz, 1ms GtG, IPS, HDR10',
        descripcionLarga: 'Siente la verdadera batalla con colores realistas. Con el primer panel Nano IPS 1ms del mundo, el UltraGear proporciona una experiencia de juego inmersiva total con mayor velocidad y calidad de imagen.',
        precio: 369.00,
        precioOferta: 339.99,
        stock: 7,
        stockMinimo: 2,
        categoria: 'perifericos',
        marca: 'LG',
        modelo: '27GR75Q-B',
        imagen: '/images/producto_monitor_lg.jpg',
        imagenes: ['/images/producto_monitor_lg.jpg'],
        enOferta: true,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2024-01-12T14:00:00Z',
        fechaActualizacion: '2024-01-12T14:00:00Z'
    },
    {
        id: 'prod-17',
        sku: 'RAM-CRU-SOD-32',
        nombre: 'Crucial RAM DDR5 32GB Kit (2x16GB) 4800MHz',
        descripcionCorta: 'SO-DIMM DDR5 para portátiles, CL40',
        descripcionLarga: 'Acelera tu portátil con la memoria DDR5 de Crucial. Diseñada para ayudar a que tu sistema funcione más rápido y fluido, esta memoria RAM para portátiles es una de las formas más fáciles y económicas de mejorar el rendimiento del sistema.',
        precio: 125.00,
        precioOferta: 115.50,
        stock: 20,
        stockMinimo: 5,
        categoria: 'ram',
        marca: 'Crucial',
        modelo: 'SO-DIMM DDR5',
        imagen: '/images/producto_ram_sodimm.jpg',
        imagenes: ['/images/producto_ram_sodimm.jpg'],
        enOferta: true,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2024-01-15T15:00:00Z',
        fechaActualizacion: '2024-01-15T15:00:00Z'
    },
    {
        id: 'prod-18',
        sku: 'PRN-HP-LJ-110',
        nombre: 'HP LaserJet M110we Impresora Láser',
        descripcionCorta: 'Monocromo, Inalámbrica, HP+',
        descripcionLarga: 'La impresora láser más pequeña del mundo de su clase, diseñada para ser eficiente con resultados de alta calidad. Incluye HP+, el sistema de impresión inteligente que te mantiene conectado y listo para imprimir desde prácticamente cualquier lugar.',
        precio: 149.99,
        precioOferta: 129.00,
        stock: 10,
        stockMinimo: 3,
        categoria: 'perifericos',
        marca: 'HP',
        modelo: 'LaserJet M110we',
        imagen: '/images/producto_impresora.jpg',
        imagenes: ['/images/producto_impresora.jpg'],
        enOferta: true,
        destacado: false,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2024-01-18T10:00:00Z',
        fechaActualizacion: '2024-01-18T10:00:00Z'
    },
    {
        id: 'prod-19',
        sku: 'CPU-AMD-7800X3D',
        nombre: 'Procesador AMD Ryzen 7 7800X3D',
        descripcionCorta: '8 núcleos, 16 hilos, 96MB L3 V-Cache, 5.0GHz Turbo',
        descripcionLarga: 'El procesador para juegos definitivo. Con la tecnología AMD 3D V-Cache de segunda generación para un rendimiento de juego increíblemente rápido, el Ryzen 7 7800X3D es el nuevo estándar para los entusiastas de PC.',
        precio: 425.00,
        precioOferta: 395.00,
        stock: 5,
        stockMinimo: 2,
        categoria: 'componentes',
        marca: 'AMD',
        modelo: 'Ryzen 7 7800X3D',
        imagen: '/images/producto_cpu_amd.jpg',
        imagenes: ['/images/producto_cpu_amd.jpg'],
        enOferta: true,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2024-01-20T09:00:00Z',
        fechaActualizacion: '2024-01-20T09:00:00Z'
    },
    {
        id: 'prod-20',
        sku: 'COL-NZX-KRK-360',
        nombre: 'NZXT Kraken 360 RGB Kit de Refrigeración Líquida',
        descripcionCorta: 'Radiador de 360mm, 3 ventiladores RGB de 120mm, Pantalla LCD',
        descripcionLarga: 'Consigue una refrigeración de alto rendimiento y añade un toque personal. El Kraken cuenta con una cara superior de bloque de agua que proporciona una visualización nítida y un control total a través de NZXT CAM.',
        precio: 229.00,
        precioOferta: 209.99,
        stock: 6,
        stockMinimo: 2,
        categoria: 'componentes',
        marca: 'NZXT',
        modelo: 'Kraken 360 RGB',
        imagen: '/images/producto_refrigeracion.jpg',
        imagenes: ['/images/producto_refrigeracion.jpg'],
        enOferta: true,
        destacado: true,
        enStock: true,
        estado: 'activo',
        fechaCreacion: '2024-01-22T12:00:00Z',
        fechaActualizacion: '2024-01-22T12:00:00Z'
    }
]

// Pedidos de prueba
export const pedidosSeed = [
    {
        id: 'pedido-1',
        numeroPedido: 'PED-2023-0123',
        clienteId: 'cliente-1',
        clienteNombre: 'Juan Pérez',
        clienteEmail: 'juan.perez@email.com',
        estado: 'pendiente',
        fecha: '2023-12-30T10:30:00Z',
        subtotal: 1099.99,
        iva: 230.90,
        gastosEnvio: 9.99,
        total: 1340.88,
        metodoPago: 'tarjeta',
        metodoEnvio: 'estandar',
        items: [
            {
                id: 'item-1',
                productoId: 'prod-1',
                nombre: 'Portátil Gaming Pro X15',
                sku: 'LAP-GAM-X15',
                descripcion: 'Intel Core i7-13700H, RTX 4070',
                cantidad: 1,
                precio: 1099.99,
                subtotal: 1099.99
            }
        ],
        direccion: 'Calle Mayor 123, 28001 Madrid'
    },
    {
        id: 'pedido-2',
        numeroPedido: 'PED-2023-0122',
        clienteId: 'cliente-2',
        clienteNombre: 'María García',
        clienteEmail: 'maria.garcia@email.com',
        estado: 'en_proceso',
        fecha: '2023-12-30T09:15:00Z',
        subtotal: 1890,
        iva: 396.90,
        gastosEnvio: 0,
        total: 2286.90,
        metodoPago: 'paypal',
        metodoEnvio: 'premium',
        items: [
            {
                id: 'item-2',
                productoId: 'prod-2',
                nombre: 'SSD NVMe Samsung 2TB',
                sku: 'SSD-SAM-2TB',
                descripcion: 'Velocidad de lectura 7450MB/s',
                cantidad: 2,
                precio: 945,
                subtotal: 1890
            }
        ],
        direccion: 'Avenida Libertad 45, 08010 Barcelona'
    },
    {
        id: 'pedido-3',
        numeroPedido: 'PED-2023-0121',
        clienteId: 'cliente-3',
        clienteNombre: 'Carlos López',
        clienteEmail: 'carlos.lopez@email.com',
        estado: 'enviado',
        fecha: '2023-12-29T16:45:00Z',
        subtotal: 599.99,
        iva: 125.90,
        gastosEnvio: 9.99,
        total: 735.88,
        metodoPago: 'transferencia',
        metodoEnvio: 'estandar',
        items: [
            {
                id: 'item-3',
                productoId: 'prod-4',
                nombre: 'Monitor Curvo 32" 4K',
                sku: 'MON-SAM-32-4K',
                descripcion: '165Hz, 1ms, HDR10+',
                cantidad: 1,
                precio: 599.99,
                subtotal: 599.99
            }
        ],
        direccion: 'Calle San Juan 67, 41003 Sevilla'
    },
    {
        id: 'pedido-4',
        numeroPedido: 'PED-2023-0120',
        clienteId: 'cliente-4',
        clienteNombre: 'Ana Martínez',
        clienteEmail: 'ana.martinez@email.com',
        estado: 'entregado',
        fecha: '2023-12-29T14:20:00Z',
        subtotal: 1254,
        iva: 263.34,
        gastosEnvio: 0,
        total: 1517.34,
        metodoPago: 'tarjeta',
        metodoEnvio: 'express',
        items: [
            {
                id: 'item-4',
                productoId: 'prod-5',
                nombre: 'CPU Intel Core i9-13900K',
                sku: 'CPU-INT-i9',
                descripcion: '24 núcleos (8P+16E)',
                cantidad: 1,
                precio: 1254,
                subtotal: 1254
            }
        ],
        direccion: 'Paseo de la Reforma 23, 50007 Zaragoza'
    },
    {
        id: 'pedido-5',
        numeroPedido: 'PED-2023-0119',
        clienteId: 'cliente-5',
        clienteNombre: 'Diego Fernández',
        clienteEmail: 'diego.fernandez@email.com',
        estado: 'cancelado',
        fecha: '2023-12-28T11:30:00Z',
        subtotal: 890,
        iva: 186.90,
        gastosEnvio: 9.99,
        total: 1086.89,
        metodoPago: 'tarjeta',
        metodoEnvio: 'estandar',
        items: [
            {
                id: 'item-5',
                productoId: 'prod-3',
                nombre: 'RAM DDR5 32GB Corsair',
                sku: 'RAM-COR-DD5-32',
                descripcion: '6000MHz CL36 RGB',
                cantidad: 5,
                precio: 178,
                subtotal: 890
            }
        ],
        direccion: 'Calle Principal 89, 28002 Madrid',
        motivoCancelacion: 'Cancelado por cliente - pago duplicado',
        fechaCancelacion: '2023-12-28T14:45:00Z'
    }
]

// Tickets SAT de prueba
export const ticketsSeed = [
    {
        id: 'ticket-1',
        numeroTicket: 'SAT-2023-0045',
        clienteId: 'cliente-1',
        clienteNombre: 'Pedro Sánchez',
        tecnicoId: 'tecnico-1',
        tecnicoNombre: 'Carlos García',
        prioridad: 'urgente',
        tipo: 'incidencia',
        asunto: 'Portátil no enciende',
        descripcion: 'El portátil no enciende al presionar el botón de encendido. No hace ningun ruido ni muestra señal de vida.',
        categoria: 'Hardware',
        estado: 'pendiente',
        notasInternas: [
            {
                id: 'n1',
                tecnicoId: 'tecnico-1',
                tecnicoNombre: 'Carlos García',
                nota: 'Ticket recibido. Pendiente de revisión.',
                fecha: '2023-12-30T08:00:00Z',
                esInterna: true
            }
        ],
        seguimientos: [
            {
                id: 's1',
                usuarioId: 'cliente-1',
                tecnicoId: null,
                tipo: 'cambio_estado',
                contenido: 'Ticket creado. Estado: Pendiente',
                esInterno: false,
                fechaCreacion: '2023-12-30T08:00:00Z'
            }
        ],
        fechaCreacion: '2023-12-30T08:00:00Z',
        fechaAsignacion: null,
        fechaResolucion: null,
        satisfaccion: null,
        valoracion: null,
        tiempoEstimado: 24,
        tiempoReal: null
    },
    {
        id: 'ticket-2',
        numeroTicket: 'SAT-2023-0044',
        clienteId: 'cliente-2',
        clienteNombre: 'Laura Rodríguez',
        tecnicoId: 'tecnico-1',
        tecnicoNombre: 'Carlos García',
        prioridad: 'alta',
        tipo: 'reparacion',
        asunto: 'SSD corrupto',
        descripcion: 'El SSD muestra errores aleatorios y se bloquea. Necesito ayuda para recuperar los datos.',
        categoria: 'Almacenamiento',
        estado: 'en_progreso',
        diagnostico: 'El SSD tiene sectores dañados. Se va a realizar recuperación de datos y clonación.',
        solucion: null,
        notasInternas: [
            {
                id: 'n1',
                tecnicoId: 'tecnico-1',
                tecnicoNombre: 'Carlos García',
                nota: 'Técnico asignado. Estado: Asignado',
                fecha: '2023-12-30T07:30:00Z',
                esInterna: true
            },
            {
                id: 'n2',
                tecnicoId: 'tecnico-1',
                tecnicoNombre: 'Carlos García',
                nota: 'Diagnóstico inicial: SSD con sectores dañados. Recomendado clonación.',
                fecha: '2023-12-30T09:00:00Z',
                esInterna: true
            }
        ],
        seguimientos: [
            {
                id: 's1',
                usuarioId: 'cliente-2',
                tecnicoId: null,
                tipo: 'cambio_estado',
                contenido: 'Ticket creado. Estado: Abierto',
                esInterna: false,
                fechaCreacion: '2023-12-30T07:30:00Z'
            },
            {
                id: 's2',
                usuarioId: 'tecnico-1',
                tecnicoId: 'tecnico-1',
                tipo: 'asignacion',
                contenido: 'Técnico asignado. Estado: Asignado',
                esInterna: true,
                fechaCreacion: '2023-12-30T07:30:00Z'
            },
            {
                id: 's3',
                usuarioId: 'tecnico-1',
                tecnicoId: 'tecnico-1',
                tipo: 'comentario',
                contenido: 'Diagnóstico: SSD con sectores dañados. Recomendado clonación.',
                esInterna: true,
                fechaCreacion: '2023-12-30T09:00:00Z'
            }
        ],
        fechaCreacion: '2023-12-30T07:30:00Z',
        fechaAsignacion: '2023-12-30T07:30:00Z',
        fechaResolucion: null,
        satisfaccion: null,
        valoracion: null,
        tiempoEstimado: 24,
        tiempoReal: null
    }
]

// Artículos de base de conocimiento de prueba
export const articulosSeed = [
    {
        id: 'articulo-1',
        titulo: 'Cómo instalar un SSD NVMe en portátil',
        contenido: 'Guía paso a paso para instalar un SSD NVMe en tu portátil. Aprende los requisitos previos, herramientas necesarias y procedimiento completo de instalación. Esta guía es para tanto Windows como Linux.',
        categoria: 'Almacenamiento',
        tags: ['SSD', 'NVMe', 'Instalación', 'Hardware', 'Portátil', 'Windows', 'Linux'],
        autor: 'Carlos García',
        autorId: 'tecnico-1',
        autorRol: 'tecnico',
        estado: 'publicado',
        vistas: 1234,
        likes: 87,
        comentarios: 15,
        fechaCreacion: '2023-12-20T10:00:00Z',
        fechaActualizacion: '2023-12-28T15:30:00Z'
    },
    {
        id: 'articulo-2',
        titulo: 'Solución a problemas de conexión WiFi',
        contenido: 'Guía completa para solucionar problemas de conexión WiFi en ordenadores portátiles y de escritorio. Incluye diagnósticos, soluciones comunes y herramientas de diagnóstico. Aborda problemas con Windows, macOS y Linux.',
        categoria: 'Redes',
        tags: ['WiFi', 'Conexión', 'Redes', 'Troubleshooting', 'Diagnóstico', 'Configuración'],
        autor: 'María Martínez',
        autorId: 'tecnico-2',
        autorRol: 'tecnico',
        estado: 'publicado',
        vistas: 890,
        likes: 65,
        comentarios: 23,
        fechaCreacion: '2023-12-18T09:00:00Z',
        fechaActualizacion: '2023-12-25T14:00:00Z'
    },
    {
        id: 'articulo-3',
        titulo: 'Guía de reparación de portátiles - Diagnóstico inicial',
        contenido: 'Aprende cómo realizar un diagnóstico inicial de tu portátil antes de llevarlo al técnico. Identifica problemas comunes de hardware y software, comprueba componentes básicos, y determina si es reparable o requiere servicio técnico.',
        categoria: 'Reparación',
        tags: ['Portátiles', 'Diagnóstico', 'Hardware', 'Software', 'Reparación'],
        autor: 'Admin Principal',
        autorId: 'admin-1',
        autorRol: 'admin',
        estado: 'publicado',
        vistas: 2345,
        likes: 156,
        comentarios: 34,
        fechaCreacion: '2023-12-15T11:00:00Z',
        fechaActualizacion: '2023-12-30T10:00:00Z'
    },
    {
        id: 'articulo-4',
        titulo: 'Actualización de BIOS y UEFI - Guía completa',
        contenido: 'Guía completa sobre cómo actualizar la BIOS o UEFI de tu ordenador. Incluye pasos de seguridad, métodos de actualización, riesgos, y recomendaciones de seguridad. Adecuada para usuarios intermedios y avanzados.',
        categoria: 'Sistema',
        tags: ['BIOS', 'UEFI', 'Actualización', 'Sistema', 'Seguridad'],
        autor: 'Diego Fernández',
        autorId: 'tecnico-3',
        autorRol: 'tecnico',
        estado: 'publicado',
        vistas: 1567,
        likes: 92,
        comentarios: 18,
        fechaCreacion: '2023-12-12T10:30:00Z',
        fechaActualizacion: '2023-12-22T16:00:00Z'
    },
    {
        id: 'articulo-5',
        titulo: 'Borrador: Instalación de GPU NVIDIA RTX 4090',
        contenido: 'Guía paso a paso para instalar una RTX 4090 en tu ordenador. Incluye requisitos de sistema (fuente de alimentación, tamaño de carcasa), fuentes de los drivers, procedimiento de instalación, y post-instalación.',
        categoria: 'Hardware',
        tags: ['GPU', 'NVIDIA', 'RTX', 'Instalación', 'Hardware'],
        autor: 'Ana Rodríguez',
        autorId: 'admin-2',
        autorRol: 'admin',
        estado: 'borrador',
        vistas: 0,
        likes: 0,
        comentarios: 0,
        fechaCreacion: '2023-12-28T14:00:00Z',
        fechaActualizacion: '2023-12-28T14:00:00Z'
    },
    {
        id: 'articulo-6',
        titulo: 'Guía de limpieza y mantenimiento de monitores',
        contenido: 'Aprende cómo limpiar y mantener tu monitor para prolongar su vida útil. Incluye productos recomendados (paños, soluciones de limpieza), frecuencia de limpieza, zonas delicadas a evitar, y mantenimiento preventivo.',
        categoria: 'Periféricos',
        tags: ['Monitor', 'Limpieza', 'Mantenimiento', 'Cuidado', 'Periféricos'],
        autor: 'Admin Principal',
        autorId: 'admin-1',
        autorRol: 'admin',
        estado: 'archivado',
        vistas: 678,
        likes: 45,
        comentarios: 8,
        fechaCreacion: '2023-11-20T09:00:00Z',
        fechaActualizacion: '2023-12-01T10:00:00Z'
    }
]
